name: post_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Routing
  go_router: ^14.6.0
  
  # Networking
  dio: ^5.4.3+1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  injectable_generator: ^2.3.2
  hive_generator: ^2.0.1
  
  # Testing
  mocktail: ^1.0.3
  bloc_test: ^9.1.0
  mockito: ^5.4.4
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
